name: CI
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
      - name: Install deps
        run: poetry install
      - name: Test
        run: poetry run pytest
