name: Publish to Test PyPI and Tag
on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  publish-test-pypi:
    runs-on: ubuntu-latest
    environment:
      name: publish-test-pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install UV
        run: pip install uv
      - name: Install dependencies
        run: uv sync
      - name: Build wheels with UV
        run: uv build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          print-hash: true

  ######################## TAG ########################
  tag:
    runs-on: ubuntu-22.04
    needs:
      - publish-test-pypi
    permissions:
      contents: write
    if: >-
      ${{
        github.event_name != 'release'
        && github.event.release.tag_name == null
        && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
          fetch-depth: "0"

      - name: Read version from pyproject.toml
        id: get-version
        run: |
          VERSION=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ steps.get-version.outputs.tag }}
          git push origin ${{ steps.get-version.outputs.tag }}
