name: Publish to PyPI
on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    environment:
      name: publish-pypi
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install UV
        run: pip install uv
      - name: Install dependencies
        run: uv sync
      - name: Build wheels with UV
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
      - name: Sign published artifacts
        uses: sigstore/gh-action-sigstore-python@v3.0.1
        with:
          inputs: ./dist/*.tar.gz ./dist/*.whl
          release-signing-artifacts: true
