name: Publish to Test PyPI
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: publish-test-pypi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
      - name: Build wheels with Poetry
        run: poetry build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          print-hash: true

  ######################## TAG ########################
  tag:
    name: Create tag from main for release
    runs-on: ubuntu-22.04
    needs:
      - publish
    permissions:
      contents: write
    if: >-
      ${{
        github.event_name != 'release'
        && github.event.release.tag_name == null
        && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        id: tag-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: ${{ github.event_name == 'pull_request' }}
          DRY_RUN: false
          BRANCH_HISTORY: compare
          RELEASE_BRANCHES: main,master
          FORCE_WITHOUT_CHANGES: true
