name: Publish to PyPI
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: publish-pypi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
      - name: Build wheels with Poetry
        run: poetry build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
      - name: Sign published artifacts
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: ./dist/*.tar.gz ./dist/*.whl
          release-signing-artifacts: true
